apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client-deployment
  labels:
    app: grpc-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-client
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
      - name: grpc-client
        image: syhlion/ithome30day-grpc-client
        env:
        - name: "ADDRESS"
          value: "grpc-server:8080"
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: grpc-client
spec:
  type: ClusterIP
  selector:
    app: grpc-client
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
